// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI9-3PKlPxddIX9mTmF6NdjXnlez9fi8U',
    appId: '1:649279040490:web:04d6c905744dc968e2e093',
    messagingSenderId: '649279040490',
    projectId: 'pharmacy-app-fae11',
    authDomain: 'pharmacy-app-fae11.firebaseapp.com',
    storageBucket: 'pharmacy-app-fae11.appspot.com',
    measurementId: 'G-CFRMCLF8DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxkNl0IjqzfUAmzlXOeq318hf3z5LvCmg',
    appId: '1:649279040490:android:da50aacc83cbc7bae2e093',
    messagingSenderId: '649279040490',
    projectId: 'pharmacy-app-fae11',
    storageBucket: 'pharmacy-app-fae11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYtvBRU2K-Aobcm3v5POUcOpw2_mZSlP0',
    appId: '1:649279040490:ios:c96181823621ee0be2e093',
    messagingSenderId: '649279040490',
    projectId: 'pharmacy-app-fae11',
    storageBucket: 'pharmacy-app-fae11.appspot.com',
    androidClientId: '649279040490-m0cjuhvooh2skhr86td8u7mjcudt54gu.apps.googleusercontent.com',
    iosClientId: '649279040490-laqf7957urks1qhqehonbifkr9bkk1dk.apps.googleusercontent.com',
    iosBundleId: 'com.example.hciManager',
  );
}
